### ISSUE TITLE
Can this appear in the Web UI?

### ISSUE THREAD

**Issue by claym** [seren/freenas-temperature-graphing#1]
The readme says "Graphs are generated in the same directory as the scripts (not the web interface)."

Is there a way to get them into the web interface?

**Comment by seren** [comment]
Not really with this scripted method. The correct way to do it would be use the existing FreeNAS status console framework instead of this scripted hack. I looked into that, but it was quicker and easier the wire this than to try and get FreeNAS compiling and figure out how to do it in an integrated way

**Comment by seren** [comment]
Though you could run a web server in a jail and have the graph PNGs written to a directory the it can serve. It wouldn't be part of the normal GUI, but it would be web accessible
